config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "/load-ajax", to: "employess#loadAjax", :defaults => { :format => :json }

  resources :employess
  # Defines the root path route ("/")
  root "employess#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy
  enum status: [:hide, :display]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/employee.rb
class Employee < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :product
end

app/models/list_attribute.rb
class ListAttribute < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :ratings
  has_many :comments
  has_many :order_details
  has_many :images, dependent: :destroy
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :orders
  has_many :ratings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employess_controller.rb
class EmployessController < ApplicationController
    before_action :load_employee, except: %i(index new create)
    def index
        @employess = Employee.all.page(params[:page]).per(6)
    end

    def show
        
    end

    def edit
        byebug
    end

    def new
        @employee = Employee.new
    end

    def loadAjax
        @employess = Employee.all.page(params[:page]).per(5)

        respond_to do |format|
            format.html
            format.json { render json: @employess.to_json }
        end
    end

    def load_employee
        @employee = Employee.find_by id: params[:id]
        return if @employee
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/views/employess/_employee.slim
.col-md-4
  .card.mb-4.shadow-sm
    =image_tag employee.image
    .card-body
      p.card-text = employee.name
      .d-flex.justify-content-between.align-items-center
        .btn-group
          = link_to "View", employess_path(employee), class: "btn btn-sm btn-outline-secondary"
          = link_to "Edit", edit_employess_path(employee), class: "btn btn-sm btn-outline-secondary"
        small.text-muted = employee.created_at

app/views/employess/_form.slim
= form_for @employee, remote: :true do |f|
  .row
    .col-md-12.col-sm-12
      .form-row
        = f.submit value: t("submit"), class: "button", id: "submit_scroll"

app/views/employess/edit.slim
.album.py-5.bg-light
  .container
    .row
     = render "form"

app/views/employess/index.slim
.album.py-5.bg-light
  .container
    .row
      = render partial: "employess/employee", collection: @employess
      = paginate @employess

app/views/employess/new.slim
.album.py-5.bg-light
  .container
    .row
     = render "form"

app/views/employess/show.slim
.col-md-4 style="margin: auto"
  .card.mb-4.shadow-sm
    = image_tag @employee.image
    .card-body
      p.card-text = @employee.name
      .d-flex.justify-content-between.align-items-center
        .btn-group
        small.text-muted = @employee.created_at

app/views/layouts/_footer.slim
footer.text-muted style=("\r\n    text-align: center;\r\n") 
  .container
    p.float-right
      a href="#"  Back to top
    p Album example is © Bootstrap, but please download and customize it for yourself!

app/views/layouts/_header.slim
  header
    #navbarHeader.collapse.bg-dark
      .container
        .row
          .col-sm-8.col-md-7.py-4
            h4.text-white About
            p.text-muted Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.
          .col-sm-4.offset-md-1.py-4
            h4.text-white Contact
            ul.list-unstyled
              li
                a.text-white href="#"  Follow on Twitter
              li
                a.text-white href="#"  Like on Facebook
              li
                a.text-white href="#"  Email me
    .navbar.navbar-dark.bg-dark.shadow-sm
      .container.d-flex.justify-content-between
        a.navbar-brand.d-flex.align-items-center href="#" 
          svg.mr-2 fill="none" height="20" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewbox=("0 0 24 24") width="20" xmlns="http://www.w3.org/2000/svg" 
            path d=("M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z") 
            circle cx="12" cy="13" r="4" 
          strong Album
        button.navbar-toggler aria-controls="navbarHeader" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarHeader" data-toggle="collapse" type="button" 
          span.navbar-toggler-icon

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title SlimFiles
    meta content="width=device-width,initial-scale=1" name="viewport" /
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload"

  body
    = render "layouts/header"
    main role="main" 
    = yield
    = render "layouts/footer"